### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by fitzoh** [sonatype-nexus-community/nancy-github-action#3]
When a new Nancy version is released, a new version of the action should be released/made available.

**Comment by zendern** [comment]
Maybe if we do this soon https://github.com/sonatype-nexus-community/nancy/issues/66 we can then easily use nancy releases as the trigger for this projects github action to now build itself and release it. 

Basically Nancy would trigger on release a repository-dispatch to this repo.
https://github.com/marketplace/actions/repository-dispatch

This repo would listen and on that trigger build a new release with the latest version of nancy. Its also probably possible via TravisCI but might be easier overall to stay in the same "sandbox" if you will.

**Comment by butuzov** [comment]
Any updates on Automating nancy releases with action?

**Comment by bhamail** [comment]
@butuzov I'm looking into a "latest" release artifact that could provide a solution to this. See: https://github.com/sonatype-nexus-community/nancy/issues/47

**Comment by bhamail** [comment]
Will now use latest nancy release by default, as of #9
